name: Terraform Workflow with Terragrunt

on:
  push:
    branches: [ "main" ]


jobs:
  terragrunt:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 1.5.5

    - name: Install Terragrunt
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.32.0/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
        terragrunt --version

    - name: Run Terragrunt
      run: |
        cd root 
        terragrunt init
        terragrunt plan
        terragrunt run-all apply
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
