name: Terraform Workflow with Terragrunt

on:
  push:
    branches: [ "main" ]


jobs:
  terragrunt:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 1.5.5

    - name: Setup terragrunt HCL
      uses: gruntwork-io/terragrunt-action@v1

    - name: Run Terragrunt
      run: |
        cd root 
        terragrunt init
        terragrunt plan
        terragrunt run-all apply
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
